services:
  app_proxy:
    environment:
      APP_HOST: axervn-pool_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/AkaCurtis/axervn-pool:v0.1.1
    restart: on-failure
    environment:
      PORT: 3000
      APP_CHANNEL: STABLE
      APP_VERSION: "0.1.1"
      STATIC_DIR: /app/static
      STATE_DIR: /data/ui/state
      POOL_CONFIG_PATH: /data/pool/config/config.json
    volumes:
      - ${APP_DATA_DIR}/data:/data
    ports:
      - "4827:4827/tcp"
